<a href="https://colab.research.google.com/github/pedrohcr16/Numpy/blob/main/Exercicio_2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**2.Crie um array de duas dimensões, no formato  9x9, com  numeros de 0 a 80 de modo crescente e selecione:**

    1.Os nº impares
    2.Os numeros pares
    3.Os multiplos de 7
    4.Os multiplos de 10
    5.Os numeros 32,33,42,43

In [ ]:
import numpy as np

In [ ]:
matriz = np.arange(81).reshape(9,9)
matriz

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [ ]:
impares = matriz % 2 == 1
matriz[impares]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79])

In [ ]:
pares = matriz % 2 == 0
matriz[pares]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80])

In [ ]:
mult_sete = matriz % 7 == 0
matriz[mult_sete]

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77])

In [ ]:
mult_dez = matriz % 10 == 0
matriz[mult_dez]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
matriz
linha = [3,3,4,4]
coluna = [5,6,6,7]
matriz[linha,coluna]

array([32, 33, 42, 43])